<!--Jquery js-->
<script src="assets/js/jquery-3.0.0.min.js"></script>
<!--Bootstrap js-->
<script src="assets/js/bootstrap.min.js"></script>
<!--ScrollIt js-->
<script src="assets/js/scrollIt.min.js"></script>
<!--Owl-Carousel js-->
<script src="assets/js/owl.carousel.min.js"></script>
<!--Ripples js-->
<script src="assets/js/jquery.ripples-min.js"></script>
<!--Barfiller js-->
<script src="assets/js/jquery.barfiller.js"></script>
<!--Animatedheadline js-->
<script src="assets/js/jquery.animatedheadline.min.js"></script>
<!-- Isotop Js -->
<script src="assets/js/isotope.pkgd.min.js"></script>
<script src="assets/js/custom-isotop.js"></script>
<!--Magnific js-->
<script src="assets/js/jquery.magnific-popup.min.js"></script>
<!--Init js-->
<script src="assets/js/init.js"></script>
<!--Main js-->
<script src="assets/js/main.js"></script>
<script src="assets/js/aos.js"></script>